services:
  backend:
    container_name: onlytanks-backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      ENVIRONMENT: docker
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
    depends_on:
      - mongo

  frontend:
    container_name: onlytanks-frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      NEXT_PUBLIC_ENVIRONMENT: docker
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  mongo:
    image: mongo:latest
    container_name: onlytanks-mongo
    environment:
      MONGO_INITDB_DATABASE: onlytanks
      MONGODB_DATA_DIR: /data/db
    volumes:
      - ./data/mongo/db:/data/db
    ports:
      - "27017:27017"
