services:
  backend:
    container_name: tankstagram-backend
    restart: unless-stopped
    build: ./backend
    environment:
      NODE_ENV: docker
    volumes:
      - ./backend/src:/app/src
    ports:
      - 8080:8080
    depends_on:
      - mongo

  frontend:
    container_name: tankstagram-frontend
    restart: unless-stopped
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      - /usr/src/app/node_modules

  mongo:
    image: mongo:latest
    container_name: tankstagram-mongo
    environment:
      MONGO_INITDB_DATABASE: tankstagram
      MONGODB_DATA_DIR: /data/db
    volumes:
      - ./data/mongo/db:/data/db
    ports:
      - "27017:27017"
