name: Backend Production CD

on:
  push:
    branches:
      - "master"
    paths:
      - "backend/**"

defaults:
  run:
    working-directory: backend

env:
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t onlytanks-backend -f Dockerfile .

      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: "node_modules"
          key: node_modules-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build

      - name: Generate Deployment Package
        run: zip -r deploy.zip . -x "*.git*" -x "node_modules*" -x "dist*"

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: "-"
          flags: "g"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Onlytanks-backend
          environment_name: Onlytanksbackend-env
          version_label: "onlytanks-backend-${{ steps.format-time.outputs.replaced }}"
          region: us-east-1
          deployment_package: backend/deploy.zip
