name: Frontend Deploy Lab

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend

env:
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID_DEV }}

jobs:
  deploy-lab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: "node_modules"
          key: node_modules-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build:lab

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./out/ s3://onlytanks-frontend-static-lab --delete
