name: Frontend CI

on:
  push:

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: "node_modules"
          key: node_modules-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: yarn lint

      - name: Build application
        run: yarn build

      - name: Run tests
        run: yarn test
